CREATE TABLE IF NOT EXISTS gdrive_invoices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gdrive_file_id VARCHAR(255) NOT NULL UNIQUE,
    file_name VARCHAR(500) NOT NULL,
    file_modified_at DATETIME,
    gdrive_year INT,
    gdrive_month INT,
    invoice_number VARCHAR(255),
    vendor_name VARCHAR(500),
    vendor_nip VARCHAR(50),
    issue_date DATE,
    amount_gross DECIMAL(12,2),
    amount_net DECIMAL(12,2),
    vat_amount DECIMAL(12,2),
    invoice_type ENUM('expense','income') DEFAULT 'expense',
    ocr_raw TEXT,
    status ENUM('pending','assigned','rejected') DEFAULT 'pending',
    assigned_record_id INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_status (status),
    INDEX idx_year_month (gdrive_year, gdrive_month)
);
