-- Ujednolicenie zapisu istniejących tagów (crm_tags.name) do formatu Tytułowego
-- (każde słowo z wielkiej litery), zgodnie z models/crm_tags.py::normalize_tag_name.
-- Słowa zapisane w całości wielkimi literami (akronimy: IT, BNI, CRM, M&A, B2B...)
-- zostają bez zmian. Dotyczy kinds: tag, industry, source, email.
-- Wygenerowano 316 zmian z 511 wierszy crm_tags.
-- Wiersz id=444 (kind='' , name='komputer') pominięty jako nieprawidłowe/osierocone dane
-- spoza zakresu ENUM kind — wymaga osobnej decyzji, nie jest ruszany przez tę migrację.

START TRANSACTION;

UPDATE crm_tags SET name='Email-Test' WHERE id=617 AND kind='tag' AND name='email-test';
UPDATE crm_tags SET name='Klient Markethub' WHERE id=551 AND kind='tag' AND name='Klient MarketHub';
UPDATE crm_tags SET name='Kuek' WHERE id=21 AND kind='tag' AND name='kuek';
UPDATE crm_tags SET name='Poszukiwania Nabywcy Mytherapy' WHERE id=22 AND kind='tag' AND name='poszukiwania nabywcy myTherapy';
UPDATE crm_tags SET name='Administracja Publiczna' WHERE id=501 AND kind='industry' AND name='Administracja publiczna';
UPDATE crm_tags SET name='Adwokat' WHERE id=352 AND kind='industry' AND name='adwokat';
UPDATE crm_tags SET name='Agenci AI' WHERE id=271 AND kind='industry' AND name='agenci AI';
UPDATE crm_tags SET name='Agencja 360' WHERE id=270 AND kind='industry' AND name='agencja 360';
UPDATE crm_tags SET name='Agencja Pracy' WHERE id=84 AND kind='industry' AND name='agencja pracy';
UPDATE crm_tags SET name='Agencje Cyfrowe' WHERE id=441 AND kind='industry' AND name='Agencje cyfrowe';
UPDATE crm_tags SET name='Agencje Reklamowe' WHERE id=476 AND kind='industry' AND name='Agencje reklamowe';
UPDATE crm_tags SET name='Akcesoria Sypialniane' WHERE id=544 AND kind='industry' AND name='Akcesoria sypialniane';
UPDATE crm_tags SET name='Analityka Biznesowa' WHERE id=85 AND kind='industry' AND name='analityka biznesowa';
UPDATE crm_tags SET name='Analityka Danych' WHERE id=263 AND kind='industry' AND name='Analityka danych';
UPDATE crm_tags SET name='Analizy Rynku' WHERE id=429 AND kind='industry' AND name='Analizy rynku';
UPDATE crm_tags SET name='Aplikacje Mobilne' WHERE id=461 AND kind='industry' AND name='Aplikacje mobilne';
UPDATE crm_tags SET name='Architektura' WHERE id=432 AND kind='industry' AND name='architektura';
UPDATE crm_tags SET name='Artykuły Spożywcze' WHERE id=239 AND kind='industry' AND name='Artykuły spożywcze';
UPDATE crm_tags SET name='Audyt Cyberbezpieczeństwa' WHERE id=502 AND kind='industry' AND name='audyt cyberbezpieczeństwa';
UPDATE crm_tags SET name='Audyty' WHERE id=281 AND kind='industry' AND name='audyty';
UPDATE crm_tags SET name='Automatyka Budynkowa' WHERE id=487 AND kind='industry' AND name='Automatyka budynkowa';
UPDATE crm_tags SET name='Automotive' WHERE id=354 AND kind='industry' AND name='automotive';
UPDATE crm_tags SET name='B2B Saas' WHERE id=534 AND kind='industry' AND name='B2B SaaS';
UPDATE crm_tags SET name='Badania I Rozwój' WHERE id=430 AND kind='industry' AND name='Badania i rozwój';
UPDATE crm_tags SET name='Badania I Rozwój AI' WHERE id=407 AND kind='industry' AND name='Badania i rozwój AI';
UPDATE crm_tags SET name='Badania Rynkowe' WHERE id=548 AND kind='industry' AND name='Badania rynkowe';
UPDATE crm_tags SET name='Badania Rynku' WHERE id=462 AND kind='industry' AND name='Badania rynku';
UPDATE crm_tags SET name='Bezpieczeństwo' WHERE id=278 AND kind='industry' AND name='bezpieczeństwo';
UPDATE crm_tags SET name='Bezpieczeństwo Danych' WHERE id=509 AND kind='industry' AND name='Bezpieczeństwo danych';
UPDATE crm_tags SET name='Bezpieczeństwo Pożarowe' WHERE id=492 AND kind='industry' AND name='Bezpieczeństwo pożarowe';
UPDATE crm_tags SET name='Big Pharma' WHERE id=277 AND kind='industry' AND name='big pharma';
UPDATE crm_tags SET name='Biuro Księgowe' WHERE id=280 AND kind='industry' AND name='biuro księgowe';
UPDATE crm_tags SET name='Bodyleasing' WHERE id=344 AND kind='industry' AND name='bodyleasing';
UPDATE crm_tags SET name='Bony' WHERE id=274 AND kind='industry' AND name='bony';
UPDATE crm_tags SET name='Budowlanka' WHERE id=89 AND kind='industry' AND name='budowlanka';
UPDATE crm_tags SET name='Budownictwo Przemysłowe' WHERE id=503 AND kind='industry' AND name='Budownictwo przemysłowe';
UPDATE crm_tags SET name='Celne' WHERE id=297 AND kind='industry' AND name='celne';
UPDATE crm_tags SET name='Centrum Medyczne' WHERE id=257 AND kind='industry' AND name='centrum medyczne';
UPDATE crm_tags SET name='Cfo' WHERE id=242 AND kind='industry' AND name='cfo';
UPDATE crm_tags SET name='Chłodnictwo' WHERE id=286 AND kind='industry' AND name='chłodnictwo';
UPDATE crm_tags SET name='Chłodnictwo I Klimatyzacja' WHERE id=32 AND kind='industry' AND name='Chłodnictwo i Klimatyzacja';
UPDATE crm_tags SET name='Ciuchy' WHERE id=307 AND kind='industry' AND name='ciuchy';
UPDATE crm_tags SET name='Coaching' WHERE id=288 AND kind='industry' AND name='coaching';
UPDATE crm_tags SET name='Coachng' WHERE id=290 AND kind='industry' AND name='coachng';
UPDATE crm_tags SET name='Cold Calling' WHERE id=93 AND kind='industry' AND name='cold calling';
UPDATE crm_tags SET name='Content Marketing' WHERE id=586 AND kind='industry' AND name='Content marketing';
UPDATE crm_tags SET name='Cyberbezpieczeństwo' WHERE id=94 AND kind='industry' AND name='cyberbezpieczeństwo';
UPDATE crm_tags SET name='Cyfrowa Transformacja' WHERE id=328 AND kind='industry' AND name='cyfrowa transformacja';
UPDATE crm_tags SET name='Diagnostyka Dziecięca' WHERE id=484 AND kind='industry' AND name='Diagnostyka dziecięca';
UPDATE crm_tags SET name='Diagnostyka Medyczna' WHERE id=401 AND kind='industry' AND name='Diagnostyka medyczna';
UPDATE crm_tags SET name='Doradztwo' WHERE id=298 AND kind='industry' AND name='doradztwo';
UPDATE crm_tags SET name='Doradztwo Biznesowe' WHERE id=249 AND kind='industry' AND name='Doradztwo biznesowe';
UPDATE crm_tags SET name='Doradztwo Celne' WHERE id=571 AND kind='industry' AND name='Doradztwo celne';
UPDATE crm_tags SET name='Doradztwo Finansowe' WHERE id=269 AND kind='industry' AND name='Doradztwo finansowe';
UPDATE crm_tags SET name='Doradztwo Gospodarcze' WHERE id=510 AND kind='industry' AND name='Doradztwo gospodarcze';
UPDATE crm_tags SET name='Doradztwo I Szkolenia' WHERE id=37 AND kind='industry' AND name='Doradztwo i szkolenia';
UPDATE crm_tags SET name='Doradztwo Innowacyjne' WHERE id=431 AND kind='industry' AND name='Doradztwo innowacyjne';
UPDATE crm_tags SET name='Doradztwo Inwestycyjne' WHERE id=333 AND kind='industry' AND name='Doradztwo inwestycyjne';
UPDATE crm_tags SET name='Doradztwo Kapitałowe' WHERE id=295 AND kind='industry' AND name='Doradztwo kapitałowe';
UPDATE crm_tags SET name='Doradztwo Naukowe' WHERE id=464 AND kind='industry' AND name='Doradztwo naukowe';
UPDATE crm_tags SET name='Doradztwo Podatkowe' WHERE id=296 AND kind='industry' AND name='doradztwo podatkowe';
UPDATE crm_tags SET name='Doradztwo Prawne' WHERE id=611 AND kind='industry' AND name='Doradztwo prawne';
UPDATE crm_tags SET name='Doradztwo Ubezpieczeniowe' WHERE id=262 AND kind='industry' AND name='doradztwo ubezpieczeniowe';
UPDATE crm_tags SET name='Doradztwo W Pozyskiwaniu Funduszy' WHERE id=447 AND kind='industry' AND name='Doradztwo w pozyskiwaniu funduszy';
UPDATE crm_tags SET name='Druk Wielkoformatowy' WHERE id=607 AND kind='industry' AND name='Druk wielkoformatowy';
UPDATE crm_tags SET name='Drukarnia' WHERE id=305 AND kind='industry' AND name='drukarnia';
UPDATE crm_tags SET name='Due Diligence' WHERE id=494 AND kind='industry' AND name='due diligence';
UPDATE crm_tags SET name='Duża' WHERE id=318 AND kind='industry' AND name='duża';
UPDATE crm_tags SET name='Dystrybucja Artykułów Biurowych' WHERE id=603 AND kind='industry' AND name='Dystrybucja artykułów biurowych';
UPDATE crm_tags SET name='Dystrybucja Artykułów Szkolnych' WHERE id=604 AND kind='industry' AND name='Dystrybucja artykułów szkolnych';
UPDATE crm_tags SET name='Działalność Społeczna' WHERE id=422 AND kind='industry' AND name='Działalność społeczna';
UPDATE crm_tags SET name='E-Commerce' WHERE id=3 AND kind='industry' AND name='E-commerce';
UPDATE crm_tags SET name='E-Learning' WHERE id=311 AND kind='industry' AND name='E-learning';
UPDATE crm_tags SET name='Ecommerce' WHERE id=495 AND kind='industry' AND name='eCommerce';
UPDATE crm_tags SET name='Edukacja Finansowa' WHERE id=316 AND kind='industry' AND name='Edukacja finansowa';
UPDATE crm_tags SET name='Efektywność Energetyczna' WHERE id=591 AND kind='industry' AND name='Efektywność energetyczna';
UPDATE crm_tags SET name='Ekspansja Międzynarodowa' WHERE id=569 AND kind='industry' AND name='Ekspansja międzynarodowa';
UPDATE crm_tags SET name='Ekspansja Rynkowa' WHERE id=467 AND kind='industry' AND name='Ekspansja rynkowa';
UPDATE crm_tags SET name='Elewacje Domów' WHERE id=229 AND kind='industry' AND name='elewacje domów';
UPDATE crm_tags SET name='Energia Odnawialna I Klimat' WHERE id=43 AND kind='industry' AND name='Energia odnawialna i klimat';
UPDATE crm_tags SET name='Esg' WHERE id=314 AND kind='industry' AND name='esg';
UPDATE crm_tags SET name='Finanse' WHERE id=102 AND kind='industry' AND name='finanse';
UPDATE crm_tags SET name='Finanse I Księgowość' WHERE id=511 AND kind='industry' AND name='Finanse i księgowość';
UPDATE crm_tags SET name='Firma Budowlana' WHERE id=103 AND kind='industry' AND name='firma budowlana';
UPDATE crm_tags SET name='Firma Konstrukcyjno-Budowlana' WHERE id=317 AND kind='industry' AND name='firma konstrukcyjno-budowlana';
UPDATE crm_tags SET name='Firmy Rodzinne' WHERE id=553 AND kind='industry' AND name='Firmy rodzinne';
UPDATE crm_tags SET name='Firmy Usługowe' WHERE id=582 AND kind='industry' AND name='firmy usługowe';
UPDATE crm_tags SET name='Fotowoltaika' WHERE id=319 AND kind='industry' AND name='fotowoltaika';
UPDATE crm_tags SET name='Fundusze Inwestycyjne' WHERE id=276 AND kind='industry' AND name='fundusze inwestycyjne';
UPDATE crm_tags SET name='Fundusze Unijne' WHERE id=420 AND kind='industry' AND name='Fundusze unijne';
UPDATE crm_tags SET name='Fuzje I Przejęcia' WHERE id=301 AND kind='industry' AND name='fuzje i przejęcia';
UPDATE crm_tags SET name='Generalne Wykonawstwo' WHERE id=240 AND kind='industry' AND name='Generalne wykonawstwo';
UPDATE crm_tags SET name='Giełda Domen' WHERE id=473 AND kind='industry' AND name='Giełda domen';
UPDATE crm_tags SET name='Gospodarka Cyfrowa Obiegu Zamkniętego' WHERE id=482 AND kind='industry' AND name='Gospodarka cyfrowa obiegu zamkniętego';
UPDATE crm_tags SET name='Gry Symulacyjne' WHERE id=439 AND kind='industry' AND name='Gry symulacyjne';
UPDATE crm_tags SET name='Handel Detaliczny' WHERE id=237 AND kind='industry' AND name='Handel detaliczny';
UPDATE crm_tags SET name='Handel Energią' WHERE id=260 AND kind='industry' AND name='Handel energią';
UPDATE crm_tags SET name='Handel Międzynarodowy' WHERE id=506 AND kind='industry' AND name='handel międzynarodowy';
UPDATE crm_tags SET name='Horeca' WHERE id=284 AND kind='industry' AND name='HoReCa';
UPDATE crm_tags SET name='Hosting Stron WWW' WHERE id=472 AND kind='industry' AND name='Hosting stron WWW';
UPDATE crm_tags SET name='Hurtownia' WHERE id=253 AND kind='industry' AND name='hurtownia';
UPDATE crm_tags SET name='Hurtownie Elektryczne' WHERE id=336 AND kind='industry' AND name='hurtownie elektryczne';
UPDATE crm_tags SET name='Instalacje Grzewcze I Sanitarne' WHERE id=526 AND kind='industry' AND name='Instalacje grzewcze i sanitarne';
UPDATE crm_tags SET name='Instalacje Teletechniczne' WHERE id=397 AND kind='industry' AND name='Instalacje teletechniczne';
UPDATE crm_tags SET name='Integracja Zespołów' WHERE id=438 AND kind='industry' AND name='Integracja zespołów';
UPDATE crm_tags SET name='Internacjonalizacja' WHERE id=322 AND kind='industry' AND name='internacjonalizacja';
UPDATE crm_tags SET name='Inwestycje' WHERE id=389 AND kind='industry' AND name='inwestycje';
UPDATE crm_tags SET name='Inwestycje Deweloperskie' WHERE id=609 AND kind='industry' AND name='Inwestycje deweloperskie';
UPDATE crm_tags SET name='Inwestycje Kapitałowe' WHERE id=404 AND kind='industry' AND name='Inwestycje kapitałowe';
UPDATE crm_tags SET name='Inwestycje Komercyjne' WHERE id=610 AND kind='industry' AND name='Inwestycje komercyjne';
UPDATE crm_tags SET name='IT Staffing' WHERE id=364 AND kind='industry' AND name='IT staffing';
UPDATE crm_tags SET name='Jęzuk Angielski' WHERE id=309 AND kind='industry' AND name='jęzuk angielski';
UPDATE crm_tags SET name='Język Angielski' WHERE id=246 AND kind='industry' AND name='język angielski';
UPDATE crm_tags SET name='Kadry I Płace' WHERE id=329 AND kind='industry' AND name='Kadry i płace';
UPDATE crm_tags SET name='Kancelaria Podatkowa' WHERE id=436 AND kind='industry' AND name='Kancelaria podatkowa';
UPDATE crm_tags SET name='Kancelaria Prawna' WHERE id=107 AND kind='industry' AND name='kancelaria prawna';
UPDATE crm_tags SET name='Karty Dostępu' WHERE id=108 AND kind='industry' AND name='karty dostępu';
UPDATE crm_tags SET name='Komunikacja' WHERE id=248 AND kind='industry' AND name='komunikacja';
UPDATE crm_tags SET name='Konferencje' WHERE id=321 AND kind='industry' AND name='konferencje';
UPDATE crm_tags SET name='Konsulting Biznesowy' WHERE id=366 AND kind='industry' AND name='Konsulting biznesowy';
UPDATE crm_tags SET name='Kontroling Finansowy' WHERE id=241 AND kind='industry' AND name='kontroling finansowy';
UPDATE crm_tags SET name='Koszulki' WHERE id=306 AND kind='industry' AND name='koszulki';
UPDATE crm_tags SET name='Księgowość' WHERE id=110 AND kind='industry' AND name='księgowość';
UPDATE crm_tags SET name='Kursy Językowe' WHERE id=621 AND kind='industry' AND name='Kursy językowe';
UPDATE crm_tags SET name='Kursy Online' WHERE id=310 AND kind='industry' AND name='Kursy online';
UPDATE crm_tags SET name='Laboratoria Analityczne' WHERE id=538 AND kind='industry' AND name='Laboratoria analityczne';
UPDATE crm_tags SET name='Leaderdship' WHERE id=289 AND kind='industry' AND name='leaderdship';
UPDATE crm_tags SET name='Logistyka' WHERE id=381 AND kind='industry' AND name='logistyka';
UPDATE crm_tags SET name='Lotnictwo' WHERE id=572 AND kind='industry' AND name='lotnictwo';
UPDATE crm_tags SET name='M&a' WHERE id=300 AND kind='industry' AND name='m&a';
UPDATE crm_tags SET name='Marketing' WHERE id=247 AND kind='industry' AND name='marketing';
UPDATE crm_tags SET name='Marketing Cyfrowy' WHERE id=465 AND kind='industry' AND name='Marketing cyfrowy';
UPDATE crm_tags SET name='Marketing Internetowy' WHERE id=491 AND kind='industry' AND name='Marketing internetowy';
UPDATE crm_tags SET name='Markety' WHERE id=112 AND kind='industry' AND name='markety';
UPDATE crm_tags SET name='Marki Odzieżowe' WHERE id=477 AND kind='industry' AND name='Marki odzieżowe';
UPDATE crm_tags SET name='Materiały Budowlane' WHERE id=528 AND kind='industry' AND name='Materiały budowlane';
UPDATE crm_tags SET name='Meble Tapicerowane' WHERE id=564 AND kind='industry' AND name='Meble tapicerowane';
UPDATE crm_tags SET name='Media Internetowe' WHERE id=315 AND kind='industry' AND name='Media internetowe';
UPDATE crm_tags SET name='Medycyna' WHERE id=256 AND kind='industry' AND name='medycyna';
UPDATE crm_tags SET name='Metalowo-Maszynowy' WHERE id=613 AND kind='industry' AND name='Metalowo-maszynowy';
UPDATE crm_tags SET name='Monitoring' WHERE id=279 AND kind='industry' AND name='monitoring';
UPDATE crm_tags SET name='Monitoring Wizyjny' WHERE id=338 AND kind='industry' AND name='Monitoring wizyjny';
UPDATE crm_tags SET name='Montaż Osłon Okiennych' WHERE id=516 AND kind='industry' AND name='Montaż osłon okiennych';
UPDATE crm_tags SET name='Nauka' WHERE id=342 AND kind='industry' AND name='nauka';
UPDATE crm_tags SET name='Nieruchomości Komercyjne' WHERE id=332 AND kind='industry' AND name='Nieruchomości komercyjne';
UPDATE crm_tags SET name='Nieruchomości Komercyjne I Mieszkaniowe' WHERE id=293 AND kind='industry' AND name='nieruchomości komercyjne i mieszkaniowe';
UPDATE crm_tags SET name='Obiekty Biurowe' WHERE id=450 AND kind='industry' AND name='Obiekty biurowe';
UPDATE crm_tags SET name='Obiekty Hotelowe' WHERE id=452 AND kind='industry' AND name='Obiekty hotelowe';
UPDATE crm_tags SET name='Obiekty Przemysłowe' WHERE id=451 AND kind='industry' AND name='Obiekty przemysłowe';
UPDATE crm_tags SET name='Obróbka Szkła' WHERE id=335 AND kind='industry' AND name='obróbka szkła';
UPDATE crm_tags SET name='Obronność' WHERE id=573 AND kind='industry' AND name='obronność';
UPDATE crm_tags SET name='Obsługa Konferencji' WHERE id=620 AND kind='industry' AND name='Obsługa konferencji';
UPDATE crm_tags SET name='Ochrona Danych' WHERE id=442 AND kind='industry' AND name='Ochrona danych';
UPDATE crm_tags SET name='Ochrona Mienia' WHERE id=399 AND kind='industry' AND name='Ochrona mienia';
UPDATE crm_tags SET name='Ochrona Zdrowia' WHERE id=568 AND kind='industry' AND name='Ochrona zdrowia';
UPDATE crm_tags SET name='Odnawialne Źródła Energii' WHERE id=259 AND kind='industry' AND name='Odnawialne źródła energii';
UPDATE crm_tags SET name='Odzież Robocza' WHERE id=115 AND kind='industry' AND name='odzież robocza';
UPDATE crm_tags SET name='Ogrody Zimowe' WHERE id=228 AND kind='industry' AND name='ogrody zimowe';
UPDATE crm_tags SET name='Opakowania Tekturowe' WHERE id=339 AND kind='industry' AND name='Opakowania tekturowe';
UPDATE crm_tags SET name='Opieka Zdrowotna' WHERE id=400 AND kind='industry' AND name='Opieka zdrowotna';
UPDATE crm_tags SET name='Opony' WHERE id=554 AND kind='industry' AND name='opony';
UPDATE crm_tags SET name='Oprogramowanie' WHERE id=221 AND kind='industry' AND name='oprogramowanie';
UPDATE crm_tags SET name='Organizacja Eventów' WHERE id=454 AND kind='industry' AND name='Organizacja eventów';
UPDATE crm_tags SET name='Organizacja Podróży' WHERE id=460 AND kind='industry' AND name='Organizacja podróży';
UPDATE crm_tags SET name='Organizacja Wydarzeń' WHERE id=619 AND kind='industry' AND name='Organizacja wydarzeń';
UPDATE crm_tags SET name='Organizator Konferencji Online' WHERE id=117 AND kind='industry' AND name='organizator konferencji online';
UPDATE crm_tags SET name='Oświetlenie Biurowe' WHERE id=512 AND kind='industry' AND name='Oświetlenie biurowe';
UPDATE crm_tags SET name='Oświetlenie Przemysłowe' WHERE id=346 AND kind='industry' AND name='oświetlenie przemysłowe';
UPDATE crm_tags SET name='Oświetlenie Zewnętrzne' WHERE id=513 AND kind='industry' AND name='Oświetlenie zewnętrzne';
UPDATE crm_tags SET name='Patenty' WHERE id=350 AND kind='industry' AND name='patenty';
UPDATE crm_tags SET name='Payroll' WHERE id=282 AND kind='industry' AND name='payroll';
UPDATE crm_tags SET name='Pizzeria' WHERE id=347 AND kind='industry' AND name='pizzeria';
UPDATE crm_tags SET name='Placówki Medyczne' WHERE id=584 AND kind='industry' AND name='Placówki medyczne';
UPDATE crm_tags SET name='Plastik' WHERE id=358 AND kind='industry' AND name='plastik';
UPDATE crm_tags SET name='Podróże Dla Firm' WHERE id=387 AND kind='industry' AND name='podróże dla firm';
UPDATE crm_tags SET name='Pokrycia Dachowe' WHERE id=529 AND kind='industry' AND name='Pokrycia dachowe';
UPDATE crm_tags SET name='Pomoc Psychologiczna' WHERE id=521 AND kind='industry' AND name='Pomoc psychologiczna';
UPDATE crm_tags SET name='Pompy Ciepła' WHERE id=287 AND kind='industry' AND name='pompy ciepła';
UPDATE crm_tags SET name='Pozycjonowanie Stron' WHERE id=368 AND kind='industry' AND name='pozycjonowanie stron';
UPDATE crm_tags SET name='Prawo / Usługi Prawnicze' WHERE id=67 AND kind='industry' AND name='Prawo / Usługi prawnicze';
UPDATE crm_tags SET name='Prawo Własności Przemysłowej' WHERE id=349 AND kind='industry' AND name='Prawo własności przemysłowej';
UPDATE crm_tags SET name='Producent' WHERE id=374 AND kind='industry' AND name='producent';
UPDATE crm_tags SET name='Produkcja Części Do Pojazdów Silnikowych' WHERE id=70 AND kind='industry' AND name='Produkcja części do pojazdów silnikowych';
UPDATE crm_tags SET name='Produkcja Części Samochodowych' WHERE id=415 AND kind='industry' AND name='Produkcja części samochodowych';
UPDATE crm_tags SET name='Produkcja Hamulców' WHERE id=353 AND kind='industry' AND name='produkcja hamulców';
UPDATE crm_tags SET name='Produkcja I Handel' WHERE id=71 AND kind='industry' AND name='Produkcja i Handel';
UPDATE crm_tags SET name='Produkcja Kart Plastikowych' WHERE id=605 AND kind='industry' AND name='Produkcja kart plastikowych';
UPDATE crm_tags SET name='Produkcja Kartonów' WHERE id=340 AND kind='industry' AND name='Produkcja kartonów';
UPDATE crm_tags SET name='Produkcja Materace' WHERE id=122 AND kind='industry' AND name='produkcja materace';
UPDATE crm_tags SET name='Produkcja Materacy' WHERE id=542 AND kind='industry' AND name='Produkcja materacy';
UPDATE crm_tags SET name='Produkcja Mebli' WHERE id=563 AND kind='industry' AND name='Produkcja mebli';
UPDATE crm_tags SET name='Produkcja Nawozów' WHERE id=549 AND kind='industry' AND name='Produkcja nawozów';
UPDATE crm_tags SET name='Produkcja Opakowań' WHERE id=355 AND kind='industry' AND name='produkcja opakowań';
UPDATE crm_tags SET name='Produkcja Oprogramowania' WHERE id=356 AND kind='industry' AND name='produkcja oprogramowania';
UPDATE crm_tags SET name='Produkcja Osłon Okiennych' WHERE id=514 AND kind='industry' AND name='Produkcja osłon okiennych';
UPDATE crm_tags SET name='Produkcja Podłóg' WHERE id=567 AND kind='industry' AND name='Produkcja podłóg';
UPDATE crm_tags SET name='Produkcja Urządzeń Laboratoryjnych' WHERE id=125 AND kind='industry' AND name='produkcja urządzeń laboratoryjnych';
UPDATE crm_tags SET name='Projektowanie' WHERE id=433 AND kind='industry' AND name='projektowanie';
UPDATE crm_tags SET name='Projektowanie Graficzne' WHERE id=608 AND kind='industry' AND name='Projektowanie graficzne';
UPDATE crm_tags SET name='Projektowanie Produktów Cyfrowych' WHERE id=417 AND kind='industry' AND name='Projektowanie produktów cyfrowych';
UPDATE crm_tags SET name='Projektowanie Wnętrz' WHERE id=545 AND kind='industry' AND name='Projektowanie wnętrz';
UPDATE crm_tags SET name='Projekty Społeczne' WHERE id=483 AND kind='industry' AND name='Projekty społeczne';
UPDATE crm_tags SET name='Przemysł Chemiczny' WHERE id=493 AND kind='industry' AND name='Przemysł chemiczny';
UPDATE crm_tags SET name='Przemysł Maszynowy' WHERE id=595 AND kind='industry' AND name='Przemysł maszynowy';
UPDATE crm_tags SET name='Przemysł Papierniczy' WHERE id=341 AND kind='industry' AND name='Przemysł papierniczy';
UPDATE crm_tags SET name='Przemysł Spożywczy' WHERE id=583 AND kind='industry' AND name='Przemysł spożywczy';
UPDATE crm_tags SET name='Przemysł Stoczniowy' WHERE id=596 AND kind='industry' AND name='Przemysł stoczniowy';
UPDATE crm_tags SET name='Przetwórstwo Tworzyw Sztucznych' WHERE id=517 AND kind='industry' AND name='Przetwórstwo tworzyw sztucznych';
UPDATE crm_tags SET name='Przychodnia Zdrowia' WHERE id=330 AND kind='industry' AND name='przychodnia zdrowia';
UPDATE crm_tags SET name='Przywództwo' WHERE id=376 AND kind='industry' AND name='przywództwo';
UPDATE crm_tags SET name='Psychiatria' WHERE id=255 AND kind='industry' AND name='psychiatria';
UPDATE crm_tags SET name='Psycholog' WHERE id=385 AND kind='industry' AND name='psycholog';
UPDATE crm_tags SET name='Psychoterapia' WHERE id=126 AND kind='industry' AND name='psychoterapia';
UPDATE crm_tags SET name='Psychoterapia Dla Dzieci' WHERE id=127 AND kind='industry' AND name='psychoterapia dla dzieci';
UPDATE crm_tags SET name='Python' WHERE id=345 AND kind='industry' AND name='python';
UPDATE crm_tags SET name='Płyty Drewniane' WHERE id=304 AND kind='industry' AND name='płyty drewniane';
UPDATE crm_tags SET name='Redukcja Emisji' WHERE id=590 AND kind='industry' AND name='Redukcja emisji';
UPDATE crm_tags SET name='Rejestracja Domen' WHERE id=471 AND kind='industry' AND name='Rejestracja domen';
UPDATE crm_tags SET name='Reklama' WHERE id=264 AND kind='industry' AND name='reklama';
UPDATE crm_tags SET name='Restauracja' WHERE id=348 AND kind='industry' AND name='restauracja';
UPDATE crm_tags SET name='Rewitalizacja Miejska' WHERE id=292 AND kind='industry' AND name='rewitalizacja miejska';
UPDATE crm_tags SET name='Rozwiązania Cyfrowe' WHERE id=428 AND kind='industry' AND name='Rozwiązania cyfrowe';
UPDATE crm_tags SET name='Rozwój Biznesu' WHERE id=427 AND kind='industry' AND name='Rozwój biznesu';
UPDATE crm_tags SET name='Rozwój Dziecka' WHERE id=486 AND kind='industry' AND name='Rozwój dziecka';
UPDATE crm_tags SET name='Rozwój Międzynarodowy' WHERE id=468 AND kind='industry' AND name='Rozwój międzynarodowy';
UPDATE crm_tags SET name='Rozwój Oprogramowania' WHERE id=410 AND kind='industry' AND name='Rozwój oprogramowania';
UPDATE crm_tags SET name='Rozwój Osobisty' WHERE id=520 AND kind='industry' AND name='Rozwój osobisty';
UPDATE crm_tags SET name='Rozwój Technologiczny' WHERE id=505 AND kind='industry' AND name='rozwój technologiczny';
UPDATE crm_tags SET name='Rynki Kapitałowe' WHERE id=406 AND kind='industry' AND name='Rynki kapitałowe';
UPDATE crm_tags SET name='Sala' WHERE id=320 AND kind='industry' AND name='sala';
UPDATE crm_tags SET name='Samorząd Zawodowy' WHERE id=411 AND kind='industry' AND name='Samorząd zawodowy';
UPDATE crm_tags SET name='Serwis Instalacji' WHERE id=527 AND kind='industry' AND name='Serwis instalacji';
UPDATE crm_tags SET name='Serwis Opon' WHERE id=555 AND kind='industry' AND name='serwis opon';
UPDATE crm_tags SET name='Serwis Pralniczy' WHERE id=498 AND kind='industry' AND name='Serwis pralniczy';
UPDATE crm_tags SET name='Serwis Samochodowy' WHERE id=602 AND kind='industry' AND name='Serwis samochodowy';
UPDATE crm_tags SET name='Serwis Urządzeń Gazowych' WHERE id=77 AND kind='industry' AND name='Serwis urządzeń gazowych';
UPDATE crm_tags SET name='Skład Budowlany' WHERE id=369 AND kind='industry' AND name='skład budowlany';
UPDATE crm_tags SET name='Software' WHERE id=357 AND kind='industry' AND name='software';
UPDATE crm_tags SET name='Software House' WHERE id=220 AND kind='industry' AND name='software house';
UPDATE crm_tags SET name='Spedycja' WHERE id=382 AND kind='industry' AND name='spedycja';
UPDATE crm_tags SET name='Sport' WHERE id=370 AND kind='industry' AND name='sport';
UPDATE crm_tags SET name='Sprzątanie' WHERE id=371 AND kind='industry' AND name='sprzątanie';
UPDATE crm_tags SET name='Sprzedaż Detaliczna' WHERE id=597 AND kind='industry' AND name='Sprzedaż detaliczna';
UPDATE crm_tags SET name='Sprzedaż Materacy' WHERE id=543 AND kind='industry' AND name='Sprzedaż materacy';
UPDATE crm_tags SET name='Sprzedaż Nieruchomości' WHERE id=434 AND kind='industry' AND name='Sprzedaż nieruchomości';
UPDATE crm_tags SET name='Sprzedaż Osłon Okiennych' WHERE id=515 AND kind='industry' AND name='Sprzedaż osłon okiennych';
UPDATE crm_tags SET name='Sprzedaż Samochodów' WHERE id=601 AND kind='industry' AND name='Sprzedaż samochodów';
UPDATE crm_tags SET name='Środki Czystości' WHERE id=373 AND kind='industry' AND name='Środki czystości';
UPDATE crm_tags SET name='Startupy' WHERE id=134 AND kind='industry' AND name='startupy';
UPDATE crm_tags SET name='Startupy Technologiczne' WHERE id=405 AND kind='industry' AND name='Startupy technologiczne';
UPDATE crm_tags SET name='Stolarka Aluminiowa' WHERE id=227 AND kind='industry' AND name='stolarka aluminiowa';
UPDATE crm_tags SET name='Stolarka Alumioniowa' WHERE id=375 AND kind='industry' AND name='stolarka alumioniowa';
UPDATE crm_tags SET name='Strategie' WHERE id=299 AND kind='industry' AND name='strategie';
UPDATE crm_tags SET name='System CRM' WHERE id=136 AND kind='industry' AND name='system CRM';
UPDATE crm_tags SET name='Systemy Alarmowe' WHERE id=593 AND kind='industry' AND name='Systemy alarmowe';
UPDATE crm_tags SET name='Systemy Bezpieczeństwa' WHERE id=398 AND kind='industry' AND name='Systemy bezpieczeństwa';
UPDATE crm_tags SET name='Systemy Paliwowe' WHERE id=536 AND kind='industry' AND name='Systemy paliwowe';
UPDATE crm_tags SET name='Systemy Przemysłowe' WHERE id=523 AND kind='industry' AND name='Systemy przemysłowe';
UPDATE crm_tags SET name='Systemy Zabezpieczeń' WHERE id=592 AND kind='industry' AND name='Systemy zabezpieczeń';
UPDATE crm_tags SET name='Sztuczna Inteligencja I Analiza Danych' WHERE id=418 AND kind='industry' AND name='Sztuczna inteligencja i analiza danych';
UPDATE crm_tags SET name='Technologie Informatyczne' WHERE id=327 AND kind='industry' AND name='technologie informatyczne';
UPDATE crm_tags SET name='Technologie Kosmiczne' WHERE id=574 AND kind='industry' AND name='technologie kosmiczne';
UPDATE crm_tags SET name='Technologie Mobilne' WHERE id=535 AND kind='industry' AND name='Technologie mobilne';
UPDATE crm_tags SET name='Telewizja Dozorowa' WHERE id=488 AND kind='industry' AND name='Telewizja dozorowa';
UPDATE crm_tags SET name='Terapia Dziecięca' WHERE id=485 AND kind='industry' AND name='Terapia dziecięca';
UPDATE crm_tags SET name='Testy Osobowości' WHERE id=377 AND kind='industry' AND name='testy osobowości';
UPDATE crm_tags SET name='Transformacja Cyfrowa' WHERE id=470 AND kind='industry' AND name='Transformacja cyfrowa';
UPDATE crm_tags SET name='Trener' WHERE id=384 AND kind='industry' AND name='trener';
UPDATE crm_tags SET name='Turystyka' WHERE id=386 AND kind='industry' AND name='turystyka';
UPDATE crm_tags SET name='Turystyka Biznesowa' WHERE id=453 AND kind='industry' AND name='Turystyka biznesowa';
UPDATE crm_tags SET name='Tworzenie Stron Internetowych' WHERE id=562 AND kind='industry' AND name='Tworzenie stron internetowych';
UPDATE crm_tags SET name='Tworzenie Stron WWW' WHERE id=585 AND kind='industry' AND name='Tworzenie stron WWW';
UPDATE crm_tags SET name='Tłumaczenia' WHERE id=388 AND kind='industry' AND name='tłumaczenia';
UPDATE crm_tags SET name='Ubezpieczenia Zdrowotne' WHERE id=402 AND kind='industry' AND name='Ubezpieczenia zdrowotne';
UPDATE crm_tags SET name='Usczelki' WHERE id=390 AND kind='industry' AND name='usczelki';
UPDATE crm_tags SET name='Uszczelnienia Techniczne' WHERE id=594 AND kind='industry' AND name='Uszczelnienia techniczne';
UPDATE crm_tags SET name='Usługi Budowlane' WHERE id=599 AND kind='industry' AND name='Usługi budowlane';
UPDATE crm_tags SET name='Usługi Cyfrowe' WHERE id=325 AND kind='industry' AND name='Usługi cyfrowe';
UPDATE crm_tags SET name='Usługi Dla Firm' WHERE id=615 AND kind='industry' AND name='Usługi dla firm';
UPDATE crm_tags SET name='Usługi Dla MŚP' WHERE id=449 AND kind='industry' AND name='Usługi dla MŚP';
UPDATE crm_tags SET name='Usługi Finansowe' WHERE id=478 AND kind='industry' AND name='Usługi finansowe';
UPDATE crm_tags SET name='Usługi Konsultingowe' WHERE id=326 AND kind='industry' AND name='usługi konsultingowe';
UPDATE crm_tags SET name='Usługi Medyczne' WHERE id=547 AND kind='industry' AND name='Usługi medyczne';
UPDATE crm_tags SET name='Usługi Montażowe' WHERE id=598 AND kind='industry' AND name='Usługi montażowe';
UPDATE crm_tags SET name='Usługi Motywacyjne' WHERE id=455 AND kind='industry' AND name='Usługi motywacyjne';
UPDATE crm_tags SET name='Usługi Prawne' WHERE id=265 AND kind='industry' AND name='usługi prawne';
UPDATE crm_tags SET name='Usługi Projektowe' WHERE id=546 AND kind='industry' AND name='Usługi projektowe';
UPDATE crm_tags SET name='Usługi Rozwojowe' WHERE id=244 AND kind='industry' AND name='Usługi rozwojowe';
UPDATE crm_tags SET name='Usługi Zdrowotne' WHERE id=539 AND kind='industry' AND name='Usługi zdrowotne';
UPDATE crm_tags SET name='Weryfikacja Firm' WHERE id=558 AND kind='industry' AND name='Weryfikacja firm';
UPDATE crm_tags SET name='Weryfikacja Podmiotów' WHERE id=145 AND kind='industry' AND name='weryfikacja podmiotów';
UPDATE crm_tags SET name='Windykacja Należności' WHERE id=559 AND kind='industry' AND name='Windykacja należności';
UPDATE crm_tags SET name='Wprawadzają Firmy Irlandzkie Do Polski' WHERE id=146 AND kind='industry' AND name='wprawadzają firmy irlandzkie do Polski';
UPDATE crm_tags SET name='Wsparcie Biznesu' WHERE id=504 AND kind='industry' AND name='wsparcie biznesu';
UPDATE crm_tags SET name='Wulkanizacja' WHERE id=556 AND kind='industry' AND name='wulkanizacja';
UPDATE crm_tags SET name='Wycena Przedsiębiorstw' WHERE id=552 AND kind='industry' AND name='Wycena przedsiębiorstw';
UPDATE crm_tags SET name='Wyceny Spółek' WHERE id=294 AND kind='industry' AND name='Wyceny spółek';
UPDATE crm_tags SET name='Wyjście Na Rynki Skandynawskie' WHERE id=302 AND kind='industry' AND name='wyjście na rynki skandynawskie';
UPDATE crm_tags SET name='Wyjście Na Rynki Zagraniczne' WHERE id=323 AND kind='industry' AND name='wyjście na rynki zagraniczne';
UPDATE crm_tags SET name='Wykończenia Wnętrz' WHERE id=82 AND kind='industry' AND name='Wykończenia wnętrz';
UPDATE crm_tags SET name='Wynajem Nieruchomości' WHERE id=435 AND kind='industry' AND name='Wynajem nieruchomości';
UPDATE crm_tags SET name='Wynajem Sprzętu' WHERE id=560 AND kind='industry' AND name='Wynajem sprzętu';
UPDATE crm_tags SET name='Własność Intelektualna' WHERE id=266 AND kind='industry' AND name='Własność intelektualna';
UPDATE crm_tags SET name='Zaopatrzenie Biurowe' WHERE id=147 AND kind='industry' AND name='zaopatrzenie biurowe';
UPDATE crm_tags SET name='Zarządzanie Nieruchomościami' WHERE id=334 AND kind='industry' AND name='Zarządzanie nieruchomościami';
UPDATE crm_tags SET name='Zarządzanie Projektami' WHERE id=224 AND kind='industry' AND name='Zarządzanie projektami';
UPDATE crm_tags SET name='Zdrowie' WHERE id=331 AND kind='industry' AND name='zdrowie';
UPDATE crm_tags SET name='Zdrowie Psychiczne' WHERE id=360 AND kind='industry' AND name='Zdrowie psychiczne';
UPDATE crm_tags SET name='Zieleń' WHERE id=372 AND kind='industry' AND name='zieleń';
UPDATE crm_tags SET name='Znaki Towarowe' WHERE id=351 AND kind='industry' AND name='znaki towarowe';
UPDATE crm_tags SET name='Ania Polak (Kuek)' WHERE id=161 AND kind='source' AND name='Ania Polak (kuek)';
UPDATE crm_tags SET name='BNI Skawina Event 2024' WHERE id=458 AND kind='source' AND name='BNI Skawina event 2024';
UPDATE crm_tags SET name='Członek BNI Milion' WHERE id=171 AND kind='source' AND name='członek BNI Milion';
UPDATE crm_tags SET name='Gość BNI' WHERE id=175 AND kind='source' AND name='gość BNI';
UPDATE crm_tags SET name='Klient MH' WHERE id=176 AND kind='source' AND name='klient MH';
UPDATE crm_tags SET name='Kuek' WHERE id=178 AND kind='source' AND name='kuek';

COMMIT;
